name: "Secure Pipeline Test - Dependency Check"

on: ["push","pull_request","workflow_dispatch"]

jobs:
    depchecktest:
      runs-on: ubuntu-latest
      name: dependencycheck_test
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Depcheck 
          uses: dependency-check/Dependendcy-Check_Action@1.0.0
          id: Depcheck 
          with:
            project: 'test'
            path: '.'
            format: 'HTML'
        -name: Upload Test results
         uses: actions/upload-artifact@master
         with:
            name: Depcheck report
            path: ${{github.workspace}}/reports
